version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgree
      POSTGRES_DB: book_store
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npm run start"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass your_redis_password --appendonly yes --save 900 1 --save 300 10 --save 60 10000
    restart: always

volumes:
  postgres_data:
  redis_data:
